version: '3'

services:
  web:
    image: sgoldyaev/timetablebot:latest
    container_name: timetablebot
    build: 
      context: .
      dockerfile: ./MIPT.BotApi/Dockerfile
    env_file:
      - /home/sgoldyaev/timetable/secrets.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_HTTPS_PORT=5001
    expose:
      - 5000
      - 5001
    ports:
      - 5000:5000
      - 5001:5001
