version: '3'

#volumes:
#  sql_data:
#    name: ./Data

services:
#  db:
#    build:
#      context: ./MIPT.Dal
#    volumes:
#      - ./MIPT.Dal/Data:/Data
#    working_dir: /Data
#    command: TimeTableDb.sqlite '.databases' '.shell ls'
  web:
    build: 
      context: .
      dockerfile: ./MIPT.BotApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_HTTPS_PORT=5001
      - ConnectionStrings:TimeTableDb=Data Source=TimeTableDb.sqlite
    expose:
      - 5000
      - 5001
    ports:
      - 5000:5000
      - 5001:5001
#    volumes:
#    - ./MIPT.Dal/Data:/Data
#    depends_on:
#      - db