name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore projects/MIPT.TimeTable.sln
    - name: Build
      run: dotnet build projects/MIPT.TimeTable.sln --configuration Debug --no-restore
    - name: Test
      run: dotnet test projects/MIPT.TimeTable.sln --verbosity=minimal
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ${{ secrets.DOCKER_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC }}
        deployment_mode: docker-compose
        copy_stack_file: false
        deploy_path: /home/sgoldyaev/timetable
        stack_file_name: projects/docker-compose.yml
        keep_files: 2
        args: up --build -d
        pull_images_first: false
        pre_deployment_command_args: BotSettings:Key=${{ secrets.BOT_KEY }} 
