name: .NET Core

on:
  push:
    branches: [ topic/initProject ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore MIPT.TimeTable.sln
    - name: Build
      run: dotnet build MIPT.TimeTable.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test MIPT.TimeTable.sln --no-restore --verbosity normal
